-- Create the table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  stock_count INT NOT NULL DEFAULT 0,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Optional trigger helper so last_updated changes automatically on update
CREATE OR REPLACE FUNCTION update_last_updated_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.last_updated = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS products_set_last_updated ON products;
CREATE TRIGGER products_set_last_updated
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION update_last_updated_column();

-- Seed initial data
INSERT INTO products (name, stock_count)
VALUES
  ('T-Shirt - Small', 50),
  ('Jeans - Blue', 25),
  ('Sneakers - Black', 12)
ON CONFLICT DO NOTHING;

-- Enable read access for anon role in Supabase
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read products" ON products;
CREATE POLICY "Allow read products"
ON products
FOR SELECT
TO anon
USING (true);
